### PR TITLE
Update README for L5 release

### PR DESCRIPTION
**Pull request by verkaufer**
Just needs a release tag for release.

### CODE REVIEW

**Comment by toin0u** [comment]
@verkaufer Thanks!

**Comment by toin0u** [comment]
Maybe it can be a good idea to write something for Laravel 4 users don't you think ?

**Comment by verkaufer** [comment]
You could make a new branch for the L5 release (maybe 0.5.x). That way you have both the L4 documentation and the L5 compatibility depending on what users want.

**Comment by toin0u** [comment]
What do you think about making a branch for the actual version and use the master for the L5 ? We gonna release Geocoder 3.0 and I think it will be a good moment to release GeocoderLaravel 1.0

**Comment by verkaufer** [comment]
That sounds perfect. So GeocoderLaravel 1.0 would be for L5 and 0.4.x would be for L4?

**Comment by toin0u** [comment]
@verkaufer exactly :) but before to release 1.0.0 I'll tag the master branch 0.5 :)

**Comment by verkaufer** [comment]
Sounds good! Just merge in this readme update when you do that :)

**Comment by toin0u** [comment]
Thanks for all your comments - It helped a lot :+1:

**Pull request merged**
