### PR TITLE
Add ability to change localization dynamically

### PR DESCRIPTION
**Pull request by amdj15**

### CODE REVIEW

**Comment by mikebronner** [comment]
Will take a look over the next few days. For some reason github is not sending out email notifications to me on things like this. grrrrrr

**Comment by mikebronner** [comment]
@willdurand Looking at this, would this be something that might be better implemented in `Geocoder\ProviderAggregator`? That way it would be available to the base package, and not be a one-off of the Laravel implementation? I think it's best to keep both in sync as much as possible when it comes to features and functionality. What do you think?

**Comment by willdurand** [comment]
That would make sense indeed. cc @Nyholm

**Comment by Nyholm** [comment]
I agree. That is a nice feature. 

It is actually already supported in the PR about QueryObject. 
See https://github.com/geocoder-php/Geocoder/pull/583/files#diff-960719e3512b26d2333128f3c57f6667

**Comment by mikebronner** [comment]
Thanks @willdurand and @Nyholm for the feedback. Will put this on the back burner and verify functionality (and make any corrective changes) once that PR is merged.

**Comment by mikebronner** [comment]
Closing for now, keeping an eye on things via the above-referenced issue.

**Pull request closed without merging**
