### PR TITLE
fix str_slug unsupported on another languages (arabic, japanese...)

### PR DESCRIPTION
**Pull request by nguyenhaiphan**
base on guide at https://stackoverflow.com/questions/22112029/strslug-alternative-for-hindi-and-arabic-strings?noredirect=1&lq=1

### CODE REVIEW

**Comment by mikebronner** [comment]
@nguyenhaiphan Thanks for this. I will post an update with this later today. :)

**Comment by mikebronner** [comment]
@nguyenhaiphan Can you provide an address in one or more of the eastern languages (Chinese, Farsi, Arabic, Japanese) -- I would like to write some unit tests for this. Thanks! :)

**Comment by mikebronner** [comment]
@nguyenhaiphan No worries, I was able to find a Japanese-character address to test with.

**Comment by mikebronner** [comment]
Quick update, just in case: this should now be implemented in version 1.1.1. Please let me know how it works for you.

**Comment by nguyenhaiphan** [comment]
Sorry for lately response. It works well now.

Thank you for your work.

**Comment by nguyenhaiphan** [comment]
By the way, could you please fix this on the 2.0Rc1 too?

**Comment by mikebronner** [comment]
Try 2.0.0-dev ... the RC1 alias caused problems in composer.

**Comment by nguyenhaiphan** [comment]
Thank you

**Pull request merged**
