### PR TITLE
Trial laravel five one

### PR DESCRIPTION
**Pull request by Keoghan**
Hi - 

I have been trialling Laravel 5.1 - and also using your package - this is a simple update to composer.json to enable it to be installed. All appears fine so far within my relatively limited use-case.

### CODE REVIEW

**Comment by devinfd** [comment]
cant update to laravel 5.1 until this is pulled in

**Comment by martinbean** [comment]
I’m in the same boat. I have a Laravel 5.1 app I want to use this in, but this package’s requirements are locked to 5.0.x

**Comment by Keoghan** [comment]
In the meantime folks, you're welcome to use my Fork. Apologies if you already know:

In composer.json, add

```javascript

"repositories": [
     {
       "type": "vcs",
       "url": "https://github.com/konsulting/GeocoderLaravel"
     }
  ]

```

and change the requirement

```javascript

"require" :
...
"toin0u/geocoder-laravel": "dev-trialLaravelFiveOne",
...

```

**Comment by mattsears18** [comment]
Thanks @Keoghan! I didn't realize that was possible.

**Comment by Keoghan** [comment]
No problem @mattsears18 - comes in handy once in a while!

**Comment by mikefrancis** [comment]
What's the progress on this?

**Comment by willdurand** [comment]
Should be fixed in [0.6.0](https://github.com/geocoder-php/GeocoderLaravel/releases/tag/0.6.0). Thanks!

**Pull request closed without merging**
