### PR TITLE
Update illuminate/support constraint to ~5.0.

### LINKED ISSUE #27: Laravel 5.1 Support
Currently, the `"illuminate/support"  : "5.0.*",` require statement makes this unable to install on Laravel 5.1, which needs `laravel/support` >= 5.1

### PR DESCRIPTION
**Pull request by CWSpear**
This adds support for Laravel 5.1

Closes #27

### CODE REVIEW

**Comment by willdurand** [comment]
thanks!

**Comment by willdurand** [comment]
@toin0u could you release a new version for this package?

**Comment by CWSpear** [comment]
Thanks @willdurand. You probably don't have access to this repo, but if you could do something about https://github.com/toin0u/Geotools-laravel/pull/9 as well, that'd be swell.

**Comment by toin0u** [comment]
I'm in vacation at the moment. I will be back in 2 weeks and I will fix it.
Sorry for that guys..

**Comment by willdurand** [comment]
@toin0u roger! enjoy ;-)

**Comment by ferrysutanto19** [comment]
i'm sorry, but is it updated yet?

**Comment by willdurand** [comment]
it isè

**Comment by ferrysutanto19** [comment]
thanks man :)

**Pull request merged**
